### ISSUE TITLE
Breaking changes upcoming for `nix` API (current master branch, future 0.24)

### ISSUE THREAD

**Issue by skrap** [lucab/libsystemd-rs#107]
It appears that nix has changed the `mq_getattr` API  in the master branch such that libsystemd no longer builds. 

Ref: https://github.com/nix-rust/nix/commit/475da53d562293553934d0e579e91f2bf3be30f7

To reproduce:
* change nix dependency to `nix = { git = "https://github.com/nix-rust/nix.git", branch = "master" }`
* `cargo build`

Result:
```
   Compiling libsystemd v0.5.0 (/home/skrap/Documents/sense/libsystemd-rs)
error[E0308]: mismatched types
   --> src/activation.rs:195:20
    |
195 |         mq_getattr(*self).is_ok()
    |                    ^^^^^ expected `&MqdT`, found `i32`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `libsystemd` due to previous error
```

I'm not sure if this is considered a semver issue with nix or a usage issue with libsystemd.

**Comment by lucab** [comment]
Thanks for the report.

> I'm not sure if this is considered a semver issue with nix or a usage issue with libsystemd.

I think it's neither of those. https://github.com/nix-rust/nix/pull/1639 is listed as breaking change in the changelog, so we'll pick up the new API and adapt to it once the next `nix` version is released.

**Comment by lucab** [comment]
@skrap if you want to draft a PR for this library using `nix` master branch, I'll be happy to keep it around until they actually tag a new release. Otherwise I think we can directly close this ticket.

**Comment by skrap** [comment]
Done!  See #108

**Comment by lunaryorn** [comment]
Closing since the upgrade was merged
