### ISSUE TITLE
Socket activation crate?

### ISSUE THREAD

**Issue by jabedude** [lucab/libsystemd-rs#29]
Hello! I wrote a tiny rust library for socket activated daemons written in rust to receive the socket file descriptor from systemd (sd_listen_fds in libsystemd). Would you be interested in using it in this crate?

**Comment by lucab** [comment]
Sure! Do you have the source for that public somewhere?

**Comment by jabedude** [comment]
Sure thing! Sorry I didn't include it originally: https://github.com/jabedude/sd-daemon-rs

**Comment by lucab** [comment]
Nice, I like the code overall.
I think there is some minor polishing that could be done around error-unwrapping and docs. If you open a PR with that, I'll be happy to review.

**Comment by jabedude** [comment]
Will do! I'll polish it up a bit and then open the PR
