### ISSUE TITLE
Services manipulation options missing

### ISSUE THREAD

**Issue by bestouff** [lucab/libsystemd-rs#3]
Hi !

Nice lib, I like it. However for it to be usable I'm missing calls to start/stop services. I'm opening this issue to be notified when it's there.

Cheers,

        Xav

**Comment by lucab** [comment]
Thanks for the report! Just for reference, that's probably one of the last thing that will be implemented, as it depends on a long chain of things up to a pure-Rust asynchronous dbus client library.
References:
 * https://github.com/diwic/dbus-rs/issues/100
 * https://github.com/srwalter/dbus-bytestream/issues/10
 * https://github.com/srwalter/dbus-serialize/issues/6

**Comment by jabedude** [comment]
@lucab Check this out: https://github.com/marcelbuesing/dbus-native/. Still a work in progress, but it's something to watch!

**Comment by lucab** [comment]
Related status update since the initial report:
 * Another library attempt is at https://gitlab.freedesktop.org/zeenix/zbus
 * I've started a WIP `serde` codec for GVariant at https://github.com/lucab/serde_gvariant

**Comment by lucab** [comment]
I'm closing this ticket now for two reasons.
The first one is that I don't plan to directly add DBus helpers here. The DBus surface of systemd service is pretty huge, and it make sense to split all of that into its own crate.
The second one is that it looks like `zbus` is getting mature enough to allow implementing this now. I've started an experimental crate at https://github.com/lucab/zbus_systemd and it already covers most of the API, but it is still very rough and non-ergonomic. But we can keep the discussion going there.
