### ISSUE TITLE
journald logging support tracking issue

### ISSUE THREAD

**Issue by jabedude** [lucab/libsystemd-rs#32]
@lucab if you're ok with it, I'd like to add support for logging to the system journal, similar to the go package.

**Comment by lucab** [comment]
I'll be super-happy to review that, yes.

A few general notes as a quick braindump:
 * the Go implementation uses a globally cached connection for historical reasons. If you need to cache something here too, feel free to have a struct (e.g. `JournalConnection`) holding it instead.
 * for temporary FD creation, there is `memfd_create` in `nix`.
 * `send` function can be implemented either in async or blocking way. We can simply focus on the latter for now, as I am not sure all the pieces are in places in other libraries to implement the former.
 * for an idea of how consumers would use journal-send logic, see https://github.com/slog-rs/journald/blob/master/src/lib.rs
