### ISSUE TITLE
logging: implement sending structured entries

### ISSUE THREAD

**Issue by lucab** [lucab/libsystemd-rs#43]
This library currently implements `logging::journal_print` for sending non-structured entries to journald.

It should also expose a `journal_send` for sending structured entries, similar to the one above but taking an additional reference to a slice of `(String, String)` tuples.

/cc @sohankunkerkar

**Comment by jlebon** [comment]
> but taking an additional reference to a slice of `(String, String)` tuples.

Minor: could we make this generic so that it just accepts any type which implements an iterator where `Item = (K, V)`? That way we could pass in e.g. HashMaps too.

**Comment by lucab** [comment]
@jlebon yes, I think that makes sense. How much generic should `K` and `V` be? We have a bunch of degrees of freedom regarding string-vs-bytes and owning-vs-references.

**Comment by jlebon** [comment]
> @jlebon yes, I think that makes sense. How much generic should K and V be? We have a bunch of degrees of freedom regarding string-vs-bytes and owning-vs-references.

Hmm, we only need references I guess, so no need to make them owning. Re. string-vs-bytes, from the POV of the API, the key has to match a restricted set (not just any UTF-8 string); though maybe we just require `AsRef<str>` and let the API error out if it doesn't match the set? (Haven't checked how the API behaves exactly there). For the values, they can technically be any binary format, but UTF-8 is recommended.

**Comment by lucab** [comment]
Ack, so I guess we are settling on something like:
```rust
pub fn journal_send<K, V>(..., vars: impl Iterator<Item = (K, V)>) -> Result<()> {
where
    K: AsRef<str>,
    V: AsRef<str>,
{ ... }
```
