### ISSUE TITLE
Remove printing from the library

### ISSUE THREAD

**Issue by ip1981** [lucab/libsystemd-rs#46]
May I suggest removal of any printing from the library, so far I can see only one place:

https://github.com/lucab/libsystemd-rs/blob/9199fac6849a2479a9ea35f42da4600f16efcd22/src/activation.rs#L151

Printing from the library may unintentionally spoil program's output/logging, I think it is better to just return an error.

**Comment by lucab** [comment]
I agree, it should bubble up the FD number and error message. Do you want to send a PR for this yourself?
Also I'm curious, were you hitting this in some real-world scenario?

**Comment by ip1981** [comment]
Oh, it just caught my eye while evaluating the library :) I might come back with a PR after some more learning.

**Comment by ip1981** [comment]
Currently I have got two options:

1. Just remove the printing :)
2. Add a new member of `SocketFd` - `Unknown(RawFd)`.

**Comment by lucab** [comment]
I'd stick to the current fallible conversion, with error returning instead of `eprintln`.

**Comment by ip1981** [comment]
> I'd stick to the current fallible conversion, with error returning instead of `eprintln`.

But it better return the file descriptor anyway, and it is still a file descriptor, we just don't know its kind. Technically, it is not an error. So `Unknown` seems natural. This would leave handling it to the consumer code. And by the way, the consumer code would still need to incorporate the raw FD of any kind to its code, so existing library classification of FDs is just a hint, no more. IMHO. I see it quite similar to the `d_type` field of the directory entry.

**Comment by lucab** [comment]
I do not disagree with your statements.
However handling unknown raw FDs is tricky (as they are just integers, and you can produce them by mistake out of thin air), so I'd like to a sit a bit and re-evaluate the whole API around them.

For the moment, I'm just happy to fix the error handling and kick out a 0.2.1 with it, in order to make sure we are not missing sockets by mistake.

**Comment by nmlt** [comment]
I saw that problem too and did this: https://github.com/nmlt/libsystemd-rs/commit/7d3b244ad15986600ba5bb461e967929848a3f3a.
I think that is what you wanted for a 0.2.1?

**Comment by ip1981** [comment]
I think the library would be the most useful in this scenario:

1. Extract FDs from systemd's environment (it may stop at this actually :))
2. Try to determine the kind of FD (because the consumer app _might_ need it anyway).
3. If it can't do the 2, still pass the FD up as is ("Unknown"). Leave it to the consumer app (this is important)

This "Unknown" kind would serve at least two purposes: protect the consumer app from the bugs in the library (unlikely, but still) or the kernel/libc/whatever, and pass yet-unknown FDs to the app (highly unlikely, but). So the library helps the consumer app, but does not get into its way, when something unforeseen happens.

**Comment by lucab** [comment]
@nmlt yes, basically that, I put up a PR at https://github.com/lucab/libsystemd-rs/pull/49.

@ip1981 yes, for 0.3 I think it makes sense to decouple `receive_*()` from the `FileDescriptor` abstraction. The original idea was to avoid forcing consumers into any `unsafe`/`RawFd` trip, but I see that it can be limiting.

**Comment by lucab** [comment]
https://github.com/lucab/libsystemd-rs/pull/49 removed printing and landed in 0.2.1.

https://github.com/lucab/libsystemd-rs/pull/52 is the draft for the larger rework proposed above.
